### ISSUE TITLE
Error when trying to execute the script from the command line

### ISSUE THREAD

**Issue by fesch89** [hashfunktion/check_innovaphone#1]
When I try to execute the script from the command line I get the following error message. I suspect that a variable was incorrectly initialized here. Unfortunately my Python knowledge is too limited to fix the error.

I'm runnig CentOS Linux release 7.7.1908 (Core) with Python 3.6

[root@icinga2 myplugins]# ./check_innovaphone.py -H "192.168.1.5" -l "admin"  -p "xxx" --command "temp" -w "50" -c "55"
Traceback (most recent call last):
  File "./check_innovaphone.py", line 570, in <module>
    main()
  File "./check_innovaphone.py", line 131, in main
    temp()
  File "./check_innovaphone.py", line 186, in temp
    if systemp > crit :
TypeError: '>' not supported between instances of 'NoneType' and 'str'

**Comment by fesch89** [comment]
Fixed it with inserting the following code after line 185:
```
   if systemp is None:
        result = "Temperature not available"

        check_exit = "OK"
        print(check_exit+' - '+result)
        ex(OK)

    elif systemp > crit :
        result = "Temperature is "+systemp+"°C | Temperature="+systemp+";"+warn+";"+crit

        check_exit = "CRITICAL"

        print(check_exit+' - '+result)
        ex(CRITICAL)
```

The value of temp was null because we are using a ipva from Innovaphone and virtual machines do not have temperature sensors :)

**Comment by hashfunktion** [comment]
Thanks for this hint, I will fix it ☺️ .
But I will turn the exit to "UNKNOWN" then when a PBX will normally have a temperature and than temp is none it's nok.
